export default {
  home: '/',
  blockList: '/blocks',
  blockDetail: '/block',
  txList: '/txs',
  txDetail: '/transaction',
  accountList: '/accounts',
  accountDetail: '/account',
  contractList: '/contracts',
  contractDetail: '/contract',
  tokenList: '/tokens',
  tokenDetail: '/token',
  nodeList: '/super-node',
  devGuides: '/developer',
  faucet: '/faucet',
  'create-wallet': '/create-wallet',
  'open-wallet': '/open-wallet',
  'wallet-account': '/wallet',
  send: '/send',
  receive: '/receive',
  wallet: '/wallet'
}
