export default {
  home: '/',
  blockList: '/blocks',
  blockDetail: '/block',
  txList: '/txs',
  txDetail: '/transaction',
  accountList: '/accounts',
  accountDetail: '/account',
  contractList: '/contracts',
  contractDetail: '/contract',
  tokenList: '/tokens',
  tokenDetail: '/token',
  nodeList: '/super-node',
  devGuides: '/developer',
  faucet: '/faucet',
  vntOfficialWebsite: 'http://www.vntchain.io/',
  vntBox: 'https://vnt.link/',
  'create-wallet': '/create-wallet',
  'open-wallet': '/open-wallet',
  'wallet-account': '/wallet',
  send: '/send',
  receive: '/receive',
  wallet: '/wallet',
  mainNet: 'https://www.vntchain.io/',
  testNet: 'https://hubscan.vnt.link/'
}
