export default {
  stats: '/stats',
  market: '/market',
  blocks: '/blocks',
  block: '/block',
  blockCount: '/blocks/count',
  txs: '/txs',
  txHistory: '/txs/history',
  priceLine: 'kline',
  txCount: '/txs/count',
  tx: '/tx',
  accounts: '/accounts',
  accountCount: '/accounts/count',
  accountDetail: '/account',
  token: '/token',
  search: '/search',
  nodes: '/nodes',
  nodesCount: '/nodes/count',
  faucet: '/hydrant',
  subscribe: '/subscribe'
}
